"""Generates the "license later" deferral/acknowledgment document.

This is deliberately NOT a licensing marketplace, checkout flow, or purchase
of any kind. It's a printable acknowledgment that a specific item (most often
a music track identified by Module E) is flagged, unresolved, and needs to be
cleared with the rights holder / brand legal team before the content is
published -- with a place for that team to sign off once it's actually
resolved.
"""
from __future__ import annotations

import io
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.config import APP_NAME


def generate_license_later_pdf(
    brand: str,
    product: str,
    items: list[dict],
) -> bytes:
    """items: list of {what_detected, why_flagged, required_action} dicts."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleX", parent=styles["Title"], fontSize=18, spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"], fontSize=10, textColor=colors.grey
    )
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], spaceBefore=14, spaceAfter=6)
    body = styles["BodyText"]
    warn = ParagraphStyle(
        "Warn",
        parent=styles["BodyText"],
        textColor=colors.HexColor("#8a5300"),
        backColor=colors.HexColor("#fff6e5"),
        borderPadding=8,
        spaceBefore=8,
        spaceAfter=8,
    )

    story = []
    story.append(Paragraph("Pre-Publication Clearance Deferral Notice", title_style))
    story.append(
        Paragraph(
            f"Generated by {APP_NAME} -- this is an acknowledgment of an unresolved item, "
            "not a license, purchase, or clearance of any kind.",
            subtitle_style,
        )
    )
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#dddddd")))
    story.append(Spacer(1, 10))

    meta_table = Table(
        [
            ["Brand", brand or "(not provided)"],
            ["Product / Campaign", product or "(not provided)"],
            ["Document generated", date.today().isoformat()],
        ],
        colWidths=[1.6 * inch, 4.4 * inch],
    )
    meta_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(meta_table)

    story.append(
        Paragraph(
            "This item is FLAGGED and UNRESOLVED. It must be cleared with the appropriate "
            "rights holder or the brand's legal/compliance team before this content is "
            f"published. {APP_NAME} identifies and flags -- it does not broker, purchase, "
            "or verify licenses.",
            warn,
        )
    )

    for i, item in enumerate(items, start=1):
        story.append(Paragraph(f"Item {i}", h2))
        rows = [
            ["What was detected", item.get("what_detected", "")],
            ["Why it's flagged", item.get("why_flagged", "")],
            ["Required action before publication", item.get("required_action", "")],
        ]
        t = Table(rows, colWidths=[1.8 * inch, 4.2 * inch])
        t.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9.5),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f2f2f2")),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.append(t)
        story.append(Spacer(1, 6))

    story.append(Paragraph("Sign-off (to be completed once resolved)", h2))
    story.append(
        Paragraph(
            "By signing below, the undersigned confirms that the item(s) above have been "
            "reviewed and appropriately licensed, cleared, or otherwise resolved, and that "
            "this content is approved for publication with respect to the item(s) flagged in "
            "this document.",
            body,
        )
    )
    story.append(Spacer(1, 24))
    signoff_table = Table(
        [
            ["Name:", "_" * 40, "Title:", "_" * 30],
            ["", "", "", ""],
            ["Signature:", "_" * 40, "Date:", "_" * 30],
        ],
        colWidths=[0.9 * inch, 2.3 * inch, 0.6 * inch, 1.8 * inch],
    )
    signoff_table.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )
    story.append(signoff_table)

    doc.build(story)
    return buf.getvalue()
